---
- hosts: all
  become: yes
  tasks:
    - name: "Nginxのインストール"
      package:
        name: nginx
        state: present
    - name: "Nginxの有効化"
      service:
        name: nginx
        state: restarted
        enabled: yes
    - name: "サービスの状態取得"
      service_facts:
    - name: "Firewalldの設定"
      firewalld:
        service: http
        permanent: true
        state: enabled
      when: ansible_facts.services["firewalld.service"].state | default("") == "running"
      register: firewalld
